### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by djoproject** [djoproject/pyshell#1]
manage to convert the whole code to pep8 standard

**Comment by djo938** [comment]
first round: simple pep8 compliance
second round: var/class/meth naming + import order + print removing
third round: replace string starting by " with ' + replace plus operator during string concanetation with parameterisation if more than two string in conca op

**Comment by djoproject** [comment]
Is it better to use parameterisation or the format method ?

**Comment by djoproject** [comment]
third round is linked to #64

**Comment by djoproject** [comment]
first and second round are done.  third one has its own issue (#64)
